test_app/config/routes.rb
Rails.application.routes.draw do
  
  # You can have the root of your site routed with "root"
  root 'welcome#index'

  get "/form" => "welcome#form"

  post "/submit" => "welcome#submit"

  get "/result" => "welcome#result"
end

test_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

test_app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

  def form
  end

  def submit
    redirect_to result_path(pizza_topping: params[:pizza_topping])
  end

  def result
    @pizza_topping = params[:pizza_topping]
    if @pizza_topping.downcase == "pepperoni"
      @comment = "Nice one."
    else
      @comment = "I can't say I agree with you."
    end 
  end
end

test_app/app/helpers/application_helper.rb
module ApplicationHelper
end

test_app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

test_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<br><br>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

test_app/app/views/welcome/form.html.erb
<div class='col-md-6 col-md-offset-3'>
  <%= form_tag "/submit", method: :post do %>
    <div class="form-group">
        <label for="pizza_topping">Pizza Topping</label>
        <br>
        <input type="text" name="pizza_topping" class="form-control" placeholder="Maybe pepperoni?">
        <br>
        <input type="submit" class="btn btn-default" value="Submit">
    </div>
  <% end %>
</div>

test_app/app/views/welcome/index.html.erb
<h1>Hello, world!</h1>

test_app/app/views/welcome/result.html.erb
<h1>So, I hear you like <%= @pizza_topping %>.</h1>
<p><%= @comment %></p>


<%= link_to "Back to form", form_path %>